# GitHub Nodejs CI
name: nodejs

on: [pull_request]
  
env:
  CI: true
  FORCE_COLOR: 2


jobs:
  run:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: ["12.x"]
        os: ["ubuntu-18.04"]

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: npm install, build, and test
        run: |
         yarn install
         yarn install --dev lerna
        env:
          CI: true
